config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'
  devise_for :users
  resources :users, only: [:show]
  resources :protos do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :tags, param: :tag_name, only: [:index, :show]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :proto
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  enum status: %i(main sub1 sub2)
  belongs_to :proto
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :proto, counter_cache: :likes_count
  belongs_to :user
end

app/models/proto.rb
class Proto < ActiveRecord::Base
  belongs_to :user
  has_many :images, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :images
  acts_as_taggable_on :tags
  validates :title, :catch_copy, presence: true
  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  has_many :protos
  has_many :likes
  has_many :comments
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:username, :team, :profile, :works, :avatar)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    current_user.comments.create(create_params)
    proto = Proto.find(params[:proto_id])
    @comments = proto.comments
  end

  private
  def create_params
    params.require(:comment).permit(:text, :proto_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, proto_id: params[:proto_id])
    @likes = Like.where(proto_id: params[:proto_id])
    @proto = Proto.find(params[:proto_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, proto_id: params[:proto_id])
    like.destroy
    @likes = Like.where(proto_id: params[:proto_id])
    @proto = Proto.find(params[:proto_id])
  end
end

app/controllers/lists/tags_controller.rb
class Lists::TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.most_used(20)
  end

  def show
    @protos = Proto.tagged_with(params[:tag_name])
  end
end

app/controllers/protos_controller.rb
class ProtosController < ApplicationController
  def index
    @protos = Proto.includes(:user, :images).order(:created_at).reverse_order.page(params[:page]).per(8)
  end

  def new
    @proto = Proto.new
    @proto.images.build
  end

  def create
    @proto = Proto.create(create_params)
    if @proto.valid?
      redirect_to :root
    else
      flash[:notice] = "Title and Catch_copy can't be blank."
      render :new
    end
  end

  def show
    @proto = Proto.includes(:user, :images).find(params[:id])
    @tags = @proto.tag_list
    @likes = Like.where(proto_id: params[:id])
      if user_signed_in?
        if @proto.like_user(current_user.id).present?
          @like = Like.where(user_id: current_user.id, proto_id: params[:id])
        end
      end
    @comment = Comment.includes(:user).new
    @comments = @proto.comments
  end

  def edit
    @proto = Proto.find(params[:id])
  end

  def update
    Proto.find(params[:id]).update(update_params)
    redirect_to :root
  end

  def destroy
    proto = Proto.find(params[:id])
    if proto.user_id == current_user.id
      proto.destroy
      redirect_to :root
    else
      redirect_to :root
    end
  end

  private
  def create_params
    params.require(:proto).permit(:title, :catch_copy, :concept, images_attributes: [:image, :status]).merge(tag_list: params[:tags]).merge(user_id: current_user.id)
  end

  def update_params
    params.require(:proto).permit(:title, :catch_copy, :concept, images_attributes: [:image, :status, :id]).merge(tag_list: params[:tags]).merge(user_id: current_user.id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.most_used(20)
  end

  def show
    @protos = Proto.includes(:user, :images).tagged_with(params[:tag_name]).order(:likes_count).reverse_order.page(params[:page]).per(8)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @protos = Proto.includes(:user, :images).order(:likes_count).reverse_order.page(params[:page]).per(8)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.includes(:protos).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.haml
.media
  .media-left
    = link_to image_tag(comment.user.avatar, style: "width: 64px; height: 64px;", alt: "64x64", class: "media-object", data: { src: "holder.js/64x64" }, data: { holder: { rendered: "true"} }, )
  .media-body
    %h4.media-heading#top-aligned-media
      = link_to comment.user.username, user_path(comment.user)
    %p
      = comment.text

app/views/comments/create.js.erb
$("#comment_text").val("");
$("#comment_list").html("<%= j(render @comments) %>");

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to root_path, class: "navbar-brand" do
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")

    .navbar-collapse.collapse.navbar-responsive-collapse
      - unless user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to "Get Started", user_session_path

      - else
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to "#", class: "dropdown-toggle", role: "button", aria: { expanded: "false" }, data: { toggle: "dropdown" } do
              = current_user.username
              %span.caret

            %ul.dropdown-menu{ role: "menu" }
              %li
                = link_to "My Page", user_path(current_user)
              %li
                = link_to "Profile Edit", edit_user_registration_path
              %li
                = link_to "Logout", destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              = link_to "New Proto", new_proto_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", http: {equiv: "Content-Type" } }/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', data: { turbolinks: { track: true } }
    = javascript_include_tag 'application', data: {turbolinks: { track: true } }
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = yield
    = render "layouts/footer"

app/views/likes/_like.html.haml
- if user_signed_in?
  - if proto.like_user(current_user.id)
    = button_to proto_like_path(like, proto_id: proto.id), method: :delete, class: "btn btn-default", id: "like-button", remote: true do
      = image_tag("icon_red_heart.svg")
      %span.num#like-sum
        = proto.likes_count
  - else
    = button_to proto_likes_path(proto), class: "btn btn-default", id: "like-button", remote: true do
      = image_tag("icon_heart.svg")
      %span.num#like-sum
        = proto.likes_count
- else
  %button.btn.btn-default#like-button
    = image_tag("icon_heart.svg")
    %span.num#like-sum
      = proto.likes_count

app/views/likes/create.js.erb
$("#like-buttons").html("<%= j(render partial: 'like', locals: { proto: @proto, likes: @likes, like: @like}) %>")

app/views/likes/destroy.js.erb
$("#like-buttons").html("<%= j(render partial: 'like', locals: { proto: @proto, likes: @likes }) %>");

app/views/protos/edit.html.haml
%div.container.proto-new
  = form_for(@proto) do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          .proto-new-title
            = f.text_field :title, autofocus: true, placeholder: "Title"

        .row
          .col-md-12
            .cover-image-upload
              = f.fields_for :images, @proto.images.main.first do |image|
                = image.file_field :image
                = image.hidden_field :status, value: :main

          .col-md-12
            %ul.proto-sub-list.list-group
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :images, @proto.images.sub1.first do |image|
                    = image.file_field :image
                    = image.hidden_field :status, value: :sub1

              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :images, @proto.images.sub2.first do |image|
                    = image.file_field :image
                    = image.hidden_field :status, value: :sub2

              %li.list-group-item.col-md-4
                .image-upload-plus
                  %span +

      .row.proto-description
        .col-md-12
          = f.text_field :catch_copy, placeholder: "Catch copy"

        .col-md-12
          = f.text_field :concept, cols: "30", rows: "4", placeholder: "Concept"

        .col-md-12
          %h4
            Tag List
          .row
            .col-md-3
              = text_field_tag "tags[]", @proto.tag_list.first, id: "prototype_tag_list", placeholder: "Web Design"

            .col-md-3
              = text_field_tag "tags[]", @proto.tag_list.second, id: "prototype_tag_list", placeholder: "UI"

            .col-md-3
              = text_field_tag "tags[]", @proto.tag_list.third, id: "prototype_tag_list", placeholder: "Application"

      .row.text-center.proto-btn
        = f.submit value: 'Publish', class: "btn btn-lg btn-primary btn-block"

app/views/protos/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li{role: "presentation"}
          = link_to "Popular PROTO", root_path
        %li.active{role: "presentation"}
          = link_to "Newest PROTO", protos_path
      = button_to "View Tags", tags_path, method: :get, class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    - @protos.each do |proto|
      .col-sm-4.col-md-3.proto-content
        .dropdown.drop_menu_location
          - if user_signed_in? && proto.user_id == current_user.id
            %button.btn.btn-default.dropdown-toggle#dropdownMenu{ type: "button", aria: { expanded: "true" }, data: { toggle: "dropdown" } }
              Action
            %ul.dropdown-menu{ aria: { labelledby: "dropdownMenu1" } }
              %li
                = link_to "Delete", "/protos/#{proto.id}", method: :delete, rel: "nofollow", data: { method: "delete" }
              %li
                = link_to "Edit", edit_proto_path(proto)
        .thumbnail
          = link_to image_tag(proto.images.main.first.image), proto_path(proto)
          .caption
            %h3
              = link_to proto.title, proto_path(proto)
            .proto-meta
              .proto-user
                = link_to proto.user.username, user_path(proto.user)
              .proto-posted
                %time
                  = time_ago_in_words proto.created_at
            %ul.proto-tag-list.list-inline
              - proto.tag_list.each do |tag|
                %li
                  = link_to tag, tag_path(tag), class: "btn btn-default"

.text-center
  %ul.pagination
    = paginate(@protos)

app/views/protos/new.html.haml
%div.container.proto-new
  = form_for(@proto) do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          .proto-new-title
            - flash.each do |key, value|
              = content_tag(:div, value, class: "#{key}")
            = f.text_field :title, autofocus: true, placeholder: "Title"

        .row
          .col-md-12
            .cover-image-upload
              = f.fields_for :images do |image|
                = image.file_field :image, onChange: "javascript: main_image_preview();", id: "main-image"
                = image.hidden_field :status, value: :main
            #main-preview.thumbnail

          .col-md-12
            %ul.proto-sub-list.list-group
              %li.list-group-item.col-md-4
                #sub1-upload.image-upload
                  = f.fields_for :images do |image|
                    = image.file_field :image, onChange: "javascript: sub1_image_preview();", id: "sub1-image"
                    = image.hidden_field :status, value: :sub1
                #sub1-preview.thumbnail

              %li.list-group-item.col-md-4
                #sub2-upload.image-upload
                  = f.fields_for :images do |image|
                    = image.file_field :image, onChange: "javascript: sub2_image_preview();", id: "sub2-image"
                    = image.hidden_field :status, value: :sub2
                #sub2-preview.thumbnail

              %li.list-group-item.col-md-4
                .image-upload-plus
                  %span +

      .row.proto-description
        .col-md-12
          = f.text_field :catch_copy, placeholder: "Catch copy"

        .col-md-12
          = f.text_field :concept, cols: "30", rows: "4", placeholder: "Concept"

        .col-md-12
          %h4
            Tag List
          .row
            .col-md-3
              = text_field_tag "tags[]", "", id: "prototype_tag_list", placeholder: "Web Design"

            .col-md-3
              = text_field_tag "tags[]", "", id: "prototype_tag_list", placeholder: "UI"

            .col-md-3
              = text_field_tag "tags[]", "", id: "prototype_tag_list", placeholder: "Application"
      .row.text-center.proto-btn
        = f.submit value: 'Publish', class: "btn btn-lg btn-primary btn-block"

app/views/protos/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to image_tag(@proto.user.avatar, alt: "64x64", class: "media-object", style: "width: 64px; height: 64px;", data: { src: "holder.js/64x64" }, data: { holder: { rendered: "true" } }), user_path(@proto.user)
        .media-body
          %h4.media-heading#top-aligned-media
            =  @proto.title
          .proto-user
            by
            = link_to @proto.user.username, user_path(@proto.user)
          %span.degree
            = @proto.user.profile
    .col-md-6.text-right
      #like-buttons
        = render partial: "/likes/like", locals: { proto: @proto, likes: @likes, like: @like }

  .row
    .col-md-9
      = link_to image_tag(@proto.images.main.first.image), proto_path(@proto), class: "img-responsive thumbnail"
    .col-md-3
      %ul.proto-sub-list.list-group
        %li.list-group-item
          = link_to image_tag(@proto.images.sub1.first.image), proto_path(@proto), class: "img-responsive thumbnail"
        %li.list-group-item
          = link_to image_tag(@proto.images.sub2.first.image), proto_path(@proto), class: "img-responsive thumbnail"

  .row.proto-description
    .col-md-3
      %h4
        Catch Copy
      %p
        = @proto.catch_copy
    .col-md-6
      %h4
        Concept
      %p
        = @proto.concept
    .col-md-3
      %h4
        Tag List
      %ul.proto-tag-list.list-inline
        - @tags.each do |tag|
          %li
            = link_to tag, tag_path(tag), class: "btn btn-default"

  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num
        = @comments.count
    .col-md-8#comment_area
      #comment_list
        = render @comments
      .form-inline
        = form_for [@proto, @comment], remote: true do |f|
          %h4
            Write a comment
          .row
            .form-group.col-md-10
              = f.text_field :text, placeholder: "Your comments", rows: "3", id: "comment_text", class: "textform-control"
              = f.hidden_field :proto_id, value: @proto.id
            .form-group.col-md-2
              = f.submit "Comment", class: "btn btn-primary"

app/views/tags/index.html.haml
.container
  .row
    .tags-list
      %h2
        Tags list
      %ul
        - @tags.each do |tag|
          .col-md-4
            = link_to tag, tag_path(tag.name), class: "btn btn-default"

app/views/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          = link_to "Popular PROTO", root_path
        %li{role: "presentation"}
          = link_to "Newest PROTO", protos_path
      = button_to "View Tags", tags_path, method: :get, class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    - @protos.each do |proto|
      .col-sm-4.col-md-3.proto-content
        .dropdown.drop_menu_location
          - if user_signed_in? && proto.user_id == current_user.id
            %button.btn.btn-default.dropdown-toggle#dropdownMenu{ type: "button", aria: { expanded: "true" }, data: { toggle: "dropdown" } }
              Action
            %ul.dropdown-menu{ aria: { labelledby: "dropdownMenu1" } }
              %li
                = link_to "Delete", "/protos/#{proto.id}", method: :delete, rel: "nofollow", data: { method: "delete" }
              %li
                = link_to "Edit", edit_proto_path(proto)
        .thumbnail
          = link_to image_tag(proto.images.main.first.image), proto_path(proto)
          .caption
            %h3
              = link_to proto.title, proto_path(proto)
            .proto-meta
              .proto-user
                = link_to proto.user.username, user_path(proto.user)
              .proto-posted
                %time
                  = time_ago_in_words proto.created_at
            %ul.proto-tag-list.list-inline
              - proto.tag_list.each do |tag|
                %li
                  = link_to tag, tag_path(tag), class: "btn btn-default"

.text-center
  %ul.pagination
    = paginate(@protos)

app/views/top/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          = link_to "Popular PROTO", root_path
        %li{role: "presentation"}
          = link_to "Newest PROTO", protos_path
      = button_to "View Tags", tags_path, method: :get, class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    - @protos.each do |proto|
      .col-sm-4.col-md-3.proto-content
        .dropdown.drop_menu_location
          - if user_signed_in? && proto.user_id == current_user.id
            %button.btn.btn-default.dropdown-toggle#dropdownMenu{ type: "button", aria: { expanded: "true" }, data: { toggle: "dropdown" } }
              Action
            %ul.dropdown-menu{ aria: { labelledby: "dropdownMenu1" } }
              %li
                = link_to "Delete", "/protos/#{proto.id}", method: :delete, rel: "nofollow", data: { method: "delete" }
              %li
                = link_to "Edit", edit_proto_path(proto)
        .thumbnail
          = link_to image_tag(proto.images.main.first.image), proto_path(proto)
          .caption
            %h3
              = link_to proto.title, proto_path(proto)
            .proto-meta
              .proto-user
                = link_to proto.user.username, user_path(proto.user)
              .proto-posted
                %time
                  = time_ago_in_words proto.created_at
            %ul.proto-tag-list.list-inline
              - proto.tag_list.each do |tag|
                %li
                  = link_to tag, tag_path(tag), class: "btn btn-default"

.text-center
  %ul.pagination
    = paginate(@protos)

app/views/users/show.html.haml
.container.user-page
  .user-nav
    .media
      .media-left
        = image_tag(@user.avatar, alt: "64*64", class: "media-object", style: "width: 64px; height: 64px;", data:{ src: "holder.js/64x64" }, data:{ holder:{ rendered: "true"} })
      .media-body
        %h4.media-heading#top-aligned-media
          Top aligned media
          %span{ class: "label label-default project-number" }
            = @user.protos.count
            %i
              Projects
        .proto-user
          %span{ class: "degree"}
            = @user.team
        .row
          .col-md-6
            %h4
              Profile
            %p
              = @user.profile
          .col-md-6
            %h4
              Works
            %p
              = @user.works

.container.proto-list
  .row
    .col-sm-4.col-md-3.proto-content
      .dropdown.drop_menu_location
        - @user.protos.each do |proto|
          .dropdown.drop_menu_location
            %button{ class: "btn btn-default dropdown-toggle", id: "dropdownMenu", type: "button", data: { toggle: "dropdown"} }
              Action
            %ul{ class: "dropdown-menu", aria: { labelledby: "dropdownMenu1"} }
              %li
                = link_to "Delete", "/protos/#{proto.id}", method: :Delete
              %li
                = link_to "Edit", edit_proto_path(proto)
          .thumbnail
            = link_to image_tag(proto.images.main.first.image), proto_path(proto)
          .caption
            %h3
              = proto.title
            .proto-meta
              .proto-user
                by
                = proto.user.username
              .proto-posted
                = time_ago_in_words proto.created_at
            %ul.proto-tag-list.list-inline
              - proto.tag_list.each do |tag|
                %li
                  = link_to tag, tag_path(tag), class: "btn btn-default"